apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: LinkAnaly
  repository: 'https://github.com/sheetung/LinkAnalyPlugin'
  version: 1.5.3
  description:
    en_US: Parses links in chats and sends screenshots for unparsed websites
    zh_Hans: 对聊天中的链接进行解析,以及针对未解析网站截图发送
  label:
    en_US: LinkAnaly
    zh_Hans: 链接解析
  icon: assets/favicon.ico
spec:
  config:
    - name: enable_github_gitee
      type: boolean
      label:
        en_US: 'Enable github/gitee feature'
        zh_Hans: '是否启用github/gitee解析'
      required: false
      default: true
    - name: enable_bilibili
      type: boolean
      label:
        en_US: 'Enable bilibili feature'
        zh_Hans: '是否启用bilibili解析'
      required: false
      default: true
    - name: enable_douyin
      type: boolean
      label:
        en_US: 'Enable douyin feature'
        zh_Hans: '是否启用抖音解析'
      required: false
      default: true
    - name: enable_acfun
      type: boolean
      label:
        en_US: 'Enable acfun feature'
        zh_Hans: '是否启用acfun解析'
      required: false
      default: true
    # - name: enable_weibo
    #   type: boolean
    #   label:
    #     en_US: 'Enable weibo feature'
    #     zh_Hans: '是否启用微博解析'
    #   required: false
    #   default: true
    # - name: enable_nga
    #   type: boolean
    #   label:
    #     en_US: 'Enable nga feature'
    #     zh_Hans: '是否启用nga解析'
    #   required: false
    #   default: true
    # - name: enable_xhs
    #   type: boolean
    #   label:
    #     en_US: 'Enable xhs feature'
    #     zh_Hans: '是否启用小红书解析'
    #   required: false
    #   default: true
    - name: screenshotsnap
      type: boolean
      label:
        en_US: 'Enable web screenshot feature'
        zh_Hans: '是否启用web截图功能'
      required: false
      default: true
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: LinkAnaly
